baseurl = "https://pouyae.ir"
title = "Pouya Esmaeili"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Pouya Esmaeili"
  info = "Software Engineer | Backend Developer | Pythonist | Gopher | Tech Junkie"
  description = "This is Pouya Esmaeili's Homepage"
  keywords = "blog,developer,personal,software,AI"
  avatarurl = "images/pouya3.jpg"
  # gravatar = "pouya.esmaeili.g@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/PouyaEsmaeili"
[[params.social]]
  name = "Stackoverflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 2
  url = "https://stackoverflow.com/users/13118327/pouya-esmaeili?tab=profile"
[[params.social]]
  name = "Linkein"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/pouya-esmaeili-9124b839/"
[[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 4
  url = "https://medium.com/@pouya.esmaeili.g"
[[params.social]]
  name = "Gmail"
  icon = "fa  fa-envelope-o fa-2x"
  weight = 5
  url = "mailto:pouya.esmaeili.g@gmail.com"
[[params.social]]
  name = "Linktree"
  icon = "fa fa-external-link fa-2x"
  weight = 6
  url = "https://linktr.ee/pouyae"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "blog/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"
[[menu.main]]
  name = "Gallery"
  weight = 4
  url  = "gallery/"
[[menu.main]]
  name = "Contact Me"
  weight = 5
  url  = "contact-me/"